BASE_PROMPT = """Add to the following source code: print statements (in the programming language of the source file)
that will print out (to the console) all relevant information about each line. The output must include the
following: The source file name, the specific scope name (if we are inside a class, function, etc.), the line #,
and the exact event taking place in detail. Details of the even must include the following (but not limited to):
Line #, type of event (variable declaration, variable assignment, function call, expression eval, or jump statement),
function name (if applicable), function return type, function parameters, variable name(s) (if applicable), variable 
values (initial and modified), variable scope, variable data type, variable modifiers (like const), resulting
effect, and any other relavent information. Please do not remove any code, and simply insert the new print statements. 
NOTE: The new statements can go directly after semi-colons. You do not need new lines or whitespace. Your output must 
be the entire source code plus all of the added print statements. Please also include Run #1, and a successful message
to indicate completion. The file name and source code language will follow.
"""

SUBSEQUENT_PROMPT = """Review the following source code already edited once by ChatGPT as well as the new source code
unedited. Please transpose all of the original inserted print statements into the new version of the source code. However,
also make any updates necessary to observe any changes made to the new iteration of source code. Follow the same schema as
the originally edited source code, but ensure to capture all changes (and specify that it is different). The way we want to
identify this execution of the program is by "Run #" which you should see in the edited code. Take whatever Run # is in the
original and simply add 1. That will be the new Run # for this execution. Aside from anything that changed in the source code,
and Run #, everything else should be identical to the edited code version. The file name and source code language will follow
and then the 
"""

# This is generated by ChatGPT:
TEST_BASE_PROMPT = """The task is to modify the given source code by adding print statements to output all relevant 
information about each line to the console. The output should include the source file name, specific scope name, line 
number, and event details such as the type of event, function name and parameters, variable name and values, variable 
scope, data type, and modifiers, resulting effect, cost of the event in milliseconds, and any other relevant information. 
The new print statements must be added directly after the semi-colons and should not disturb the source code in any way. 
The output must contain the entire source code and added print statements, and must be syntactically correct as it will 
be compiled and run. For loops take place over the same few lines, so there's no need to add any integers to line numbers. 
The program details such as the run number (this prompt will be run only once), current date/time, real time of the entire 
run, user time of the entire run, system time of the entire run, and any other pertinent details should be output at the 
end of the file. It is important to organize all program details well and avoid using libraries outside of the standard or 
already imported libraries. The file name and source code language will be provided.
"""

def initial_prompt(file_type, file_name):
	prompt = BASE_PROMPT + 'The source code language is {file_type} and the file name is {file_name}.'
	return prompt

def sub_prompt(file_type, file_name):
	prompt = SUBSEQUENT_PROMPT + 'The source code language is {file_type} and the file name is {file_name}.'
	return prompt
